WITH TEMP AS (
    SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * SUM(SALES) AS 'PARTIAL_SALES'
    FROM BOOK B, AUTHOR A, BOOK_SALES S
    WHERE S.SALES_DATE LIKE '2022-01%' AND B.AUTHOR_ID = A.AUTHOR_ID
                                       AND B.BOOK_ID = S.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.BOOK_ID, B.CATEGORY
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PARTIAL_SALES) AS 'TOTAL_SALES'
FROM TEMP
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;