SELECT A.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES as BS
JOIN BOOK as B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR as AU ON B.AUTHOR_ID = AU.AUTHOR_ID
JOIN (SELECT DISTINCT AUTHOR_ID FROM BOOK) A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
GROUP BY A.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
